# Generated by Django 5.0.4 on 2024-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('present', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('leaves', models.IntegerField()),
            ],
        ),
    ]
