# Generated by Django 5.0.4 on 2024-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
